[package]
name = "climsimburn"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "51.0.0"
arrow-csv = "51.0.0"
burn = { version = "0.13.2", features = ["train", "wgpu"] }
derive-new = "0.6.0"
num-traits = "0.2.19"
